#!/bin/sh 
let retval=0
if [ ! -f /usr/local/lib/libaquaterm.1.?.?.dylib ]; then
    let retval=$retval+1
fi
if [ ! -f /usr/X11R6/bin/xinit ]; then
    let retval=$retval+2
fi
if [ $retval -gt 0 ]; then
    let retval=$retval+47
fi
exit $retval